name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Yarn
      run: npm install -g yarn # Extra Step
    - name: Run test suite
      run: |
        yarn
        yarn test
